### ISSUE TITLE
Need to dive back into gfplot and do the following

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfiphc#3]
- [x] Issue #44 - num_sets unhardwire
- [x] Need to keep track of num_sets observed and num_sets going forward (not just proportion), for all and 20 hooks
- [x] https://github.com/pbs-assess/gfsynopsis/issues/49  - data for IPHC map. Since final year should base it on coastwide stations and all hooks, so already calculated for each species as Series C. Make NA's if empty. Need lat and lon for sets also. Wasn't Series C, was just all the raw data in `set_counts`.
- [ ] Issue #40 - no. hooks deployed in first 20
- [ ] Issue #45 - bunch of minor things, not all needed
- [x] Do hook competition calculations if time, first write up calculations in gfsynopsis.
